var namespacesig =
[
    [ "impl", "namespacesig_1_1impl.html", "namespacesig_1_1impl" ],
    [ "AbsoluteError", "structsig_1_1_absolute_error.html", "structsig_1_1_absolute_error" ],
    [ "array", "classsig_1_1array.html", "classsig_1_1array" ],
    [ "assign_div_t", "structsig_1_1assign__div__t.html", "structsig_1_1assign__div__t" ],
    [ "assign_minus_t", "structsig_1_1assign__minus__t.html", "structsig_1_1assign__minus__t" ],
    [ "assign_mult_t", "structsig_1_1assign__mult__t.html", "structsig_1_1assign__mult__t" ],
    [ "assign_plus_t", "structsig_1_1assign__plus__t.html", "structsig_1_1assign__plus__t" ],
    [ "BinaryDistance", "structsig_1_1_binary_distance.html", "structsig_1_1_binary_distance" ],
    [ "CanberraDistance", "structsig_1_1_canberra_distance.html", "structsig_1_1_canberra_distance" ],
    [ "CosineSimilarity", "structsig_1_1_cosine_similarity.html", "structsig_1_1_cosine_similarity" ],
    [ "decrement_t", "structsig_1_1decrement__t.html", "structsig_1_1decrement__t" ],
    [ "div_t", "structsig_1_1div__t.html", "structsig_1_1div__t" ],
    [ "Histgram", "classsig_1_1_histgram.html", "classsig_1_1_histgram" ],
    [ "identity_t", "structsig_1_1identity__t.html", "structsig_1_1identity__t" ],
    [ "increment_t", "structsig_1_1increment__t.html", "structsig_1_1increment__t" ],
    [ "JS_Divergence", "structsig_1_1_j_s___divergence.html", "structsig_1_1_j_s___divergence" ],
    [ "KL_Divergence", "structsig_1_1_k_l___divergence.html", "structsig_1_1_k_l___divergence" ],
    [ "MahalanobisDistance", "structsig_1_1_mahalanobis_distance.html", "structsig_1_1_mahalanobis_distance" ],
    [ "ManageConvergence", "classsig_1_1_manage_convergence.html", "classsig_1_1_manage_convergence" ],
    [ "ManageConvergenceSimple", "classsig_1_1_manage_convergence_simple.html", "classsig_1_1_manage_convergence_simple" ],
    [ "MaxNorm", "structsig_1_1_max_norm.html", "structsig_1_1_max_norm" ],
    [ "MinkowskiDistance", "structsig_1_1_minkowski_distance.html", "structsig_1_1_minkowski_distance" ],
    [ "minus_t", "structsig_1_1minus__t.html", "structsig_1_1minus__t" ],
    [ "mult_t", "structsig_1_1mult__t.html", "structsig_1_1mult__t" ],
    [ "Norm", "structsig_1_1_norm.html", "structsig_1_1_norm" ],
    [ "Percent", "classsig_1_1_percent.html", "classsig_1_1_percent" ],
    [ "plus_t", "structsig_1_1plus__t.html", "structsig_1_1plus__t" ],
    [ "RelativeError", "structsig_1_1_relative_error.html", "structsig_1_1_relative_error" ],
    [ "SimpleRandom", "classsig_1_1_simple_random.html", "classsig_1_1_simple_random" ],
    [ "TagDealer", "classsig_1_1_tag_dealer.html", "classsig_1_1_tag_dealer" ],
    [ "TimeWatch", "classsig_1_1_time_watch.html", "classsig_1_1_time_watch" ],
    [ "ZenHanReplace", "classsig_1_1_zen_han_replace.html", "classsig_1_1_zen_han_replace" ]
];